spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/alcohol_calendar
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8
springdoc:
  api-docs:
    path: swagger-api

